config/routes.rb
EasyJobs::Application.routes.draw do
  devise_for :admins, :controllers => { :sessions => "sessions" }

  resources :servers do
    member do
      get :delete
      post :create_blank_job, as: "create_blank_job_for"
    end
  end

  resources :jobs do
    member do
      get :run
      get :token_run
      get :timestats
      delete :timestats, to: "jobs#destroy_timestats"
      get :delete
    end
  end

  resources :admins do
    member do
      get :delete
      post :edit
    end
  end

  get '/settings', to: "settings#index"
  scope '/settings' do
    put :edit_types, to: "settings#update_types"
    put :edit_interpreters, to: "settings#update_interpreters"
    put :edit_constants, to: "settings#update_constants"
    get '/constant/:id', to: "settings#get_constant", as: "get_constant"
    put '/constant/:id', to: "settings#update_content_of_constant", as: "edit_content_of_constant"
  end

  root to: "jobs#index"

  get '/token_login/*token', to: "application#token_login", as: "token_login", format: false

  namespace :api do
    namespace :v1 do
      get :help
      get :parameters
      delete :tokens, as: "revoke_token"
      resources :jobs, only: [:index, :show] do
        get :run
      end
    end
  end

  

end

app/views/admins/_form.html.haml
= form_for @admin do |f|
  - if @admin.errors.any?
    #error_explanation
      %h2= t('error.admin', count: @admin.errors.count)
      %ul
        - @admin.errors.full_messages.each do |msg|
          %li= msg
  .panel
    %h3= f.label :username
    .pc= f.text_field :username, autofocus: true
  .panel
    %h3= f.label :email
    .pc= f.text_field :email
  .panel
    %h3= f.label :password
    .pc= f.password_field :password, placeholder: @admin.id ? t('leave_blank_if_no_changes') : nil
  - unless @admin.id
    .separator
  .actions
    = f.submit t('Save'), class: "button button-green"

- if @admin.id
  .separator
  - if @show_qrcode == 1
    .panel
      %h3= t('Google_Authenticator_QRCode')
      .pc
        .qrcode{ data: { text: generate_google_authenticator_qrcode_for_admin(@admin) } }
    .actions= link_to t('Back'), edit_admin_path(@admin), class: "button button-blue"
  - else
    = form_tag edit_admin_path(@admin) do
      .panel
        %h3= label_tag :password, t('helpers.label.admin.password')
        .pc= password_field_tag :password, nil, placeholder: t('your_current_password')
      .actions= submit_tag t('View_Google_Authenticator_QRCode'), name: "google", class: "button button-blue"
  .separator
  - if @show_qrcode == 2 or @show_qrcode == 3
    - if @show_qrcode == 2
      .panel
        %h3= t('Mobile_Authentication_QRCode')
        .pc
          .qrcode{ data: { text: generate_mobile_authentication_qrcode_for_admin(@admin) } }
      .actions= link_to t('Back'), edit_admin_path(@admin), class: "button button-blue"
    - if @show_qrcode == 3
      .actions= link_to t('Authenticate_Now'), 'easyjobs://' + generate_mobile_authentication_qrcode_for_admin(@admin), class: "button button-green"
      .actions= link_to t('Back'), edit_admin_path(@admin), class: "button button-blue"
  - else
    = form_tag edit_admin_path(@admin) do
      .panel
        %h3= label_tag :password, t('helpers.label.admin.password')
        .pc= password_field_tag :password, nil, placeholder: t('your_current_password')
      .actions= submit_tag t('Get_Mobile_Authentication_QRCode'), name: "mobile", class: "button button-blue"
      .actions= submit_tag t('Get_Authentication_Link'), name: "link", class: "button button-blue"

app/views/admins/_menu.html.haml
#submenu.button_group
  = link_to admins_path, class: "button button-list#{active_action? %w(index)}" do
    %span.icon= t('Listing_Admins')
  - admin_id = @admin.try(:id)
  - admin_id = session[:admin_id] if admin_id.nil? and session[:admin_id].present?
  - if admin_id.present?
    = link_to admin_path(admin_id), class: "button button-details#{active_action? %w(show)}" do
      %span.icon= t('Admin_Details')
    = link_to edit_admin_path(admin_id), class: "button button-edit#{active_action? %w(edit update)}" do
      %span.icon= t('Edit_Admin')
    = link_to delete_admin_path(admin_id), title: t('Delete_Admin'), class: "button button-delete button-red delete#{active_action? %w(delete)}" do
      %span.icon
  = link_to new_admin_path, class: "button button-new button-green#{active_action? %w(new create)}" do
    %span.icon= t('New_Admin')
.menu_div

app/views/admins/delete.html.haml
= render 'menu'

.panel.max
  %h3= t("Deleting_Admin", admin: @admin.username)
  .confirm
    = t('Delete_Admin_Confirm')
    .buttons
      = link_to t('Delete_Admin_Yes'), admin_path(@admin), method: :delete, data: { confirm: t('Delete_Admin_Confirm') }, class: "button button-red"

app/views/admins/edit.html.haml
= render 'menu'

= render 'form'

app/views/admins/index.html.haml
= render 'menu'
:css
  @media only screen and (max-width: 480px) {
    table#admins td:nth-of-type(1):before { content: "ID"; }
    table#admins td:nth-of-type(2):before { content: "#{t('helpers.label.admin.username')}"; }
    table#admins td:nth-of-type(3):before { content: "#{t('helpers.label.admin.email')}"; }
    table#admins td:nth-of-type(4):before { content: "#{t('helpers.label.admin.Last_Sign_In_At')}"; }
  }
%table#admins.list
  %thead
    %tr
      %th ID
      %th= t('helpers.label.admin.username')
      %th= t('helpers.label.admin.email')
      %th.date= t('helpers.label.admin.Last_Sign_In_At')
  %tfoot
    %tr
      %td{ colspan: 4 }
        = t("admin", count: @admins.size)
  - @admins.each do |admin|
    %tr
      %td= admin.id
      %td
        = link_to admin.username, admin
        - if current_admin.id == admin.id
          %em
            %small= t("this_is_you")
      %td= admin.email
      %td.date
        - if admin.last_sign_in_at.present?
          %abbr.timeago{ title: admin.last_sign_in_at.getutc.iso8601 }
            = admin.last_sign_in_at
        - else
          (n/a)

%script<= raw jquery_timeago_tranlations

app/views/admins/new.html.haml
= render 'menu'

= render 'form'

app/views/admins/show.html.haml
= render 'menu'

.panel.float
  %h3= t('helpers.label.admin.username')
  .pc
    = @admin.username
.panel.float
  %h3= t('helpers.label.admin.email')
  .pc
    = @admin.email
.panel.float
  %h3= t('helpers.label.admin.Sign_In_Count')
  .pc
    = @admin.sign_in_count
.panel.float
  %h3= t('helpers.label.admin.Current_Sign_In_At')
  .pc
    - if @admin.current_sign_in_at.present?
      %abbr.timeago{ title: @admin.current_sign_in_at.getutc.iso8601 }
        = @admin.current_sign_in_at
    - else
      (n/a)
.panel.float
  %h3= t('helpers.label.admin.Last_Sign_In_At')
  .pc
    - if @admin.last_sign_in_at.present?
      %abbr.timeago{ title: @admin.last_sign_in_at.getutc.iso8601 }
        = @admin.last_sign_in_at
    - else
      (n/a)
.panel.float
  %h3= t('helpers.label.admin.Created_At')
  .pc
    %abbr.timeago{ title: @admin.created_at.getutc.iso8601 }
      = @admin.created_at
.panel.float
  %h3= t('helpers.label.admin.Current_Sign_In_IP')
  .pc
    = @admin.current_sign_in_ip.presence || "(n/a)"
.panel.float
  %h3= t('helpers.label.admin.Last_Sign_In_IP')
  .pc
    = @admin.last_sign_in_ip.presence || "(n/a)"
.panel.float
  %h3= t('helpers.label.admin.Updated_At')
  .pc
    %abbr.timeago{ title: @admin.updated_at.getutc.iso8601 }
      = @admin.updated_at
.clear

%script<= raw jquery_timeago_tranlations