config/routes.rb
EasyJobs::Application.routes.draw do
  devise_for :admins, :controllers => { :sessions => "sessions" }

  resources :servers do
    member do
      get :delete
      post :create_blank_job, as: "create_blank_job_for"
    end
  end

  resources :jobs do
    member do
      get :run
      get :token_run
      get :timestats
      delete :timestats, to: "jobs#destroy_timestats"
      get :delete
    end
  end

  resources :admins do
    member do
      get :delete
      post :edit
    end
  end

  get '/settings', to: "settings#index"
  scope '/settings' do
    put :edit_types, to: "settings#update_types"
    put :edit_interpreters, to: "settings#update_interpreters"
    put :edit_constants, to: "settings#update_constants"
    get '/constant/:id', to: "settings#get_constant", as: "get_constant"
    put '/constant/:id', to: "settings#update_content_of_constant", as: "edit_content_of_constant"
  end

  root to: "jobs#index"

  get '/token_login/*token', to: "application#token_login", as: "token_login", format: false

  namespace :api do
    namespace :v1 do
      get :help
      get :parameters
      delete :tokens, as: "revoke_token"
      resources :jobs, only: [:index, :show] do
        get :run
      end
    end
  end

  

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :server
  belongs_to :interpreter
  belongs_to :type
  has_many :time_stats, dependent: :destroy
  validates_presence_of :name, :script
  validates_uniqueness_of :name
end

app/controllers/api/v1/jobs_controller.rb
class Api::V1::JobsController < Api::V1Controller
  layout false

  def index
    render json: Job.joins('LEFT JOIN servers ON servers.id = jobs.server_id')
      .joins('LEFT JOIN types ON types.id = jobs.type_id')
      .select('jobs.id, jobs.name, servers.name as server_name, types.id as type_id, types.name as type_name')
  end

  def show
    job = Job.where('jobs.id = ?', params[:id]).first
    server = job.server
    if server
      server = job.server.attributes
      server.delete("password")
    end
    require 'digest/md5'
    script_hash = Digest::MD5.hexdigest(job.script)
    render json: {
      job: job,
      interpreter: job.interpreter,
      server: server,
      hash: script_hash
    }
  end

  def run
    _p = params.has_key?(:parameters) ? { parameters: params[:parameters] } : {}
    p = params.permit(:token, :hash, :exit_if_non_zero).merge(_p).to_query
    p = "?" + p unless p.empty?
    @eventSource = token_run_job_path(params[:job_id]) + p
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :delete, :run, :token_run, :destroy, :timestats, :destroy_timestats]

  helper_method :get_parameters_of
  def get_parameters_of(script)
    script.scan(/[^%]?%{(.+?)}/).flatten(1).uniq
  end

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs_by_type = Job.all.order("type_id ASC").group_by(&:type)
    @jobs_count = Job.count
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    require 'digest/md5'
    @job_parameters = Constant.where("name = ?", "job_parameters").first || []
    @job_parameters = YAML::load @job_parameters.content unless @job_parameters.blank?
    @script_hash = Digest::MD5.hexdigest(@job.script)
  end

  def timestats
    created_at = @job.time_stats.pluck(:created_at).last(12).map{|x| x.to_i }
    real = @job.time_stats.pluck(:real).last(12)

    created_at.push created_at[0] if created_at.length == 1
    real.push real[0] if real.length == 1

    render json: { created_at: created_at, real: real, mean_time: @job.mean_time }
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    create_job_with job_params
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    if params.has_key?(:save_and_go_back) and params.has_key?(:referrer)
      destination = params[:referrer]
    else
      destination = @job
    end

    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to destination, notice: t('notice.job.updated') }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def delete
  end

  def destroy_timestats
    @job.time_stats.clear
    @job.update({ mean_time: nil })
    respond_to do |format|
      format.html { redirect_to @job, notice: t('notice.job.timestats_deleted') }
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.time_stats.clear
    @job.destroy
    session[:job_id] = nil
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: t('notice.job.deleted') }
    end
  end

  # GET /jobs/1/run
  include ActionController::Live
  def run
    __run
  end

  skip_before_action :authenticate, only: [:token_run]
  before_action :authenticate_with_token, only: [:token_run]
  def token_run
    __run
  end

  private
  def __run
    require 'streamer/sse'
    require 'net/ssh'
    require 'net/scp'
    require 'benchmark'
    require 'digest/md5'

    response.headers['Content-Type'] = 'text/event-stream'
    sse = Streamer::SSE.new(response.stream)
    begin
      raise t("sse.please_select_server") if @job.server.nil?
      raise t("sse.please_reload_page") unless
        params.has_key?(:hash) and Digest::MD5.hexdigest(@job.script) == params[:hash]

      key_data = @job.server.constant.try(:content).presence || nil

      ssh_params = [@job.server.host, @job.server.username,
        password: @job.server.password, key_data: key_data, timeout: 5]

      if @job.interpreter.try(:path)
        time_used = Benchmark.measure {
          Net::SSH.start *ssh_params do |ssh|
            if @job.interpreter.upload_script_first
              script = @job.script
              script.gsub!(/\r\n?/, "\n")
              ssh.scp.upload!(StringIO.new(script), "/tmp/easyjobs_script") do |ch, name, sent, total|
                sse.write(status(t('sse.upload_progress', name: name, percent: "#{(sent.to_f * 100 / total.to_f).to_i}", sent: sent, total: total)))
              end
              cmd = "#{@job.interpreter.path} /tmp/easyjobs_script"
              sse.write(status(t('sse.running_command', command: cmd)))
              ssh.exec!(cmd) do |channel, stream, data|
                sse.write(data)
              end
            else
              ssh.open_channel do |channel|
                channel.exec(@job.interpreter.path) do |ch, success|
                  channel.send_data @job.script
                  channel.eof!
                  channel.on_data do |ch,data|
                    sse.write(data)
                  end
                end
              end
            end
          end
        }
        record_and_output_real_time time_used, @job, sse
      else

        # job without interpreter (default)
        script = @job.script
        script.gsub!(/\r\n?/, "\n")
        script.gsub!(/\\\n\s*/, "")

        # param substitute
        good_param = 0
        parameters = get_parameters_of(script)
        parameters.each do |p|
          good_param = good_param + 1 if params.has_key?(:parameters) and 
            params[:parameters].has_key?(p) and params[:parameters][p].length > 0
        end

        raise t("sse.params_not_provided") if good_param != parameters.count

        script = script % params[:parameters].symbolize_keys if good_param > 0

        exit_if_non_zero = (params.has_key?(:exit_if_non_zero) && params[:exit_if_non_zero] == "1")

        # execute commands
        time_used = Benchmark.measure {
          Net::SSH.start *ssh_params do |ssh|
            script.lines.each do |line|
              line.strip!
              next if line.empty? or line[0] == "#"
              exit_code = 0
              ssh.exec!(line) do |channel, stream, data|
                sse.write(data)
                channel.on_request("exit-status") do |ch,data|
                  exit_code = data.read_long
                end
              end
              raise t("sse.exit_with_status_code", code: exit_code) if exit_if_non_zero and exit_code > 0
            end
          end
        }
        record_and_output_real_time time_used, @job, sse

      end
    rescue Timeout::Error
      sse.write(status(t('sse.timed_out')))
    rescue Net::SSH::AuthenticationFailed
      sse.write(status(t('sse.auth_failed')))
    rescue IOError
      # the client disconnects
    rescue Exception => e
      sse.write(status(e.message))
    ensure
      sse.close
    end
  end

    def status(string)
      "> #{string}\n"
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])

      # remeber last entered job
      session[:job_id] = params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :interpreter_id, :script, :server_id, :type_id)
    end

    def record_and_output_real_time(time_used, job, sse)
      TimeStat.create([{ real: time_used.real, job_id: job.id, job_script_size: job.script.length }])
      mean_time = job.time_stats.average(:real)
      job.update({ mean_time: mean_time })
      sse.write(status(t('sse.time_used', time: time_used.real)))
      sse.write(status(t('sse.mean_time', time: mean_time)))
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= t('error.job', count: @job.errors.count)
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  .panel.float
    %h3= f.label :name
    .pc= f.text_field :name, autofocus: true
  .panel.float
    %h3= f.label :server_id
    .pc
      .select= f.collection_select :server_id, Server.all, :id, :name, include_blank: t("none")
  .panel.float
    %h3= f.label :interpreter_id
    .pc
      .select= f.collection_select :interpreter_id, Interpreter.all, :id, :path, include_blank: t("default")
  .panel.max
    %h3= f.label :script
    .pc= f.text_area :script, size: "80x10"
  .panel.float
    %h3= f.label :type_id
    .pc
      .select= f.collection_select :type_id, Type.all, :id, :name, include_blank: t("none")
  .separator.clear
  .actions
    - if @job.id
      = hidden_field_tag "referrer", request.referrer
      = f.submit t('Save_and_go_back_to_previous_page'), name: "save_and_go_back", class: "button button-green"
    = f.submit t('Save'), class: "button button-green"

app/views/jobs/_menu.html.haml
#submenu.button_group
  = link_to jobs_path, class: "button button-list#{active_action? %w(index)}" do
    %span.icon= t('Listing_Jobs')
  - job_id = @job.try(:id)
  - job_id = session[:job_id] if job_id.nil? and session[:job_id].present?
  - if job_id.present?
    = link_to job_path(job_id), class: "button button-details#{active_action? %w(show)}" do
      %span.icon= t('Job_Details')
    = link_to edit_job_path(job_id), class: "button button-edit#{active_action? %w(edit update)}" do
      %span.icon= t('Edit_Job')
    = link_to delete_job_path(job_id), title: t('Delete_Job'), class: "button button-delete button-red delete#{active_action? %w(delete)}" do
      %span.icon
  = link_to new_job_path, class: "button button-new button-green#{active_action? %w(new create)}" do
    %span.icon= t('New_Job')
.menu_div

app/views/jobs/delete.html.haml
= render 'menu'

.panel.max
  %h3= t("Deleting_Job", job: @job.name)
  .confirm
    = t('Delete_Job_Confirm')
    .buttons
      = link_to t('Delete_Job_Yes'), job_path(@job), method: :delete, data: { confirm: t('Delete_Job_Confirm') }, class: "button button-red"
    = t('Delete_Job_Others')
    .buttons
      = link_to t('Delete_Time_Stats_Only'), timestats_job_path(@job), method: :delete, data: { confirm: t('Delete_Time_Stats_Confirm') }, class: "button button-red"

app/views/jobs/index.html.haml
= render 'menu'
:css
  @media only screen and (max-width: 480px) {
    table#jobs td.job_name:before { content: "#{t('helpers.label.job.name')}"; }
    table#jobs td.server:before { content: "#{t('helpers.label.job.server')}"; }
    table#jobs td.date:before { content: "#{t('helpers.label.job.Updated_At')}"; }
  }
%table#jobs.list.with_types
  %thead
    %tr
      %th.type= t('helpers.label.job.type')
      %th.job_name= t('helpers.label.job.name')
      %th.server= t('helpers.label.job.server')
      %th.date= t('helpers.label.job.Updated_At')
  %tfoot
    %tr
      %td{ colspan: 4 }
        = t("job", count: @jobs_count)
  %tbody
    - @jobs_by_type.each do |type, jobs|
      - jobs.each_with_index do |job, index|
        %tr
          - if index == 0
            %td.type{ rowspan: jobs.size }= type.try(:name) || t("Orphans")
          %td.job_name
            = link_to job.name, job
            %span.interpreter
              = job.interpreter.try(:path).presence || t("Script")
            = link_to t('Edit_Job'), edit_job_path(job), title: t('Edit_Job'), class: "edit"
          %td.server
            -if job.server.nil?
              = t('none')
            -else
              = link_to job.server.name, server_path(job.server)
            = link_to(t('Change_Key'), edit_server_path(job.server), title: t('Change_Key'), class: "key") if job.server.try(:constant).present?
          %td.date
            %abbr.timeago{ title: job.updated_at.getutc.iso8601 }
              = job.updated_at

%script<= raw jquery_timeago_tranlations

app/views/jobs/show.html.haml
= render 'menu'

.panel.float
  %h3= t('helpers.label.job.name')
  .pc
    = @job.name
.panel.float
  %h3= t('helpers.label.job.server')
  .pc
    = @job.server ? link_to(@job.server.name, edit_server_path(@job.server)) : t("none")
    - if @job.server.present?
      = link_to(t('Change_Key'), edit_server_path(@job.server), title: t('Change_Key'), class: "key") if @job.server.constant.present?
      %small= "(#{@job.server.username}@#{@job.server.host})"
.panel.float
  %h3= t('helpers.label.job.Mean_Time')
  #mean_time.pc{ data: { mean_time: @job.mean_time.presence || "0" }}
    = @job.mean_time.present? ? "#{@job.mean_time} s" : t("not_started_yet")
.panel.max
  %h3= @job.interpreter.try(:path).presence || t("Script")
  %pre#script.pc.script.CodeMirror.cm-s-monokai{ data: { interpreter: @job.interpreter.try(:path) } }
    = preserve do
      = @job.script

- if @job.interpreter.nil? # only for jobs without interpreters (default)
  - get_parameters_of(@job.script).each do |param|
    .panel.float
      %h3= param
      .pc
        = text_field_tag nil, nil, id: nil, class: "custom_param", placeholder: t("value"), data: { param: param }
        - if @job_parameters.include? param
          .select
            = select_tag nil, options_for_select([[t('select'),'']] + @job_parameters[param]), id: nil, class: "fill_custom_param"
        - else
          %small= t("no_param_found", param: param)
.clear

- if @job.interpreter.nil? # only for jobs without interpreters (default)
  .misc
    = check_box_tag :exit_if_non_zero, 1, true
    = label_tag :exit_if_non_zero, t("exit_if_non_zero")

#progress.progress.progress-blue.right-side
  %span

.field
  = link_to t('Run'), '', data: { cancel: t('Cancel'), run: t('Run'), to: run_job_path(@job), hash: @script_hash }, id: "run_job", class: "button button-blue"

.clear
.separator

%pre#output= t('pending')

.separator
.panel.max
  %h3= t('Statistics')
  #chart{ class: ("never" if @job.time_stats.empty?), data: { json: timestats_job_path(@job) } }
    - if @job.time_stats.empty?
      %p= t('not_started_yet')

%script= raw i18n_javascript_for_current_controller