config/routes.rb
EasyJobs::Application.routes.draw do
  devise_for :admins, :controllers => { :sessions => "sessions" }

  resources :servers do
    member do
      get :delete
      post :create_blank_job, as: "create_blank_job_for"
    end
  end

  resources :jobs do
    member do
      get :run
      get :token_run
      get :timestats
      delete :timestats, to: "jobs#destroy_timestats"
      get :delete
    end
  end

  resources :admins do
    member do
      get :delete
      post :edit
    end
  end

  get '/settings', to: "settings#index"
  scope '/settings' do
    put :edit_types, to: "settings#update_types"
    put :edit_interpreters, to: "settings#update_interpreters"
    put :edit_constants, to: "settings#update_constants"
    get '/constant/:id', to: "settings#get_constant", as: "get_constant"
    put '/constant/:id', to: "settings#update_content_of_constant", as: "edit_content_of_constant"
  end

  root to: "jobs#index"

  get '/token_login/*token', to: "application#token_login", as: "token_login", format: false

  namespace :api do
    namespace :v1 do
      get :help
      get :parameters
      delete :tokens, as: "revoke_token"
      resources :jobs, only: [:index, :show] do
        get :run
      end
    end
  end

  

end

app/models/server.rb
class Server < ActiveRecord::Base
  has_many :jobs
  belongs_to :constant
  validates_presence_of :name, :host, :username
  validates_uniqueness_of :name
  attr_accessor :need_password
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :delete, :destroy, :create_blank_job]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: t('notice.server.created') }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def create_blank_job
    job_params = Hash.new
    job_params[:name] = t('default_script_name', server: @server.name)
    job_params[:script] = t('default_script')
    job_params[:server_id] = @server.id
    create_job_with job_params
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    if params.has_key?(:save_and_go_back) and params.has_key?(:referrer)
      destination = params[:referrer]
    else
      destination = @server
    end

    if params[:server].has_key?(:need_password) && params[:server].has_key?(:password)
      case params[:server][:need_password]
        when "0"
          params[:server][:password] = ""
        when "1"
          if params[:server][:password].empty? then
            params[:server].delete :password
          end
      end
    end

    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to destination, notice: t('notice.server.updated') }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def delete
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    session[:server_id] = nil
    respond_to do |format|
      format.html { redirect_to servers_url, notice: t('notice.server.deleted') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
      if params.has_key?(:server) and params[:server].has_key?(:need_password)
        @server.need_password = params[:server][:need_password]
      else
        @server.need_password = !@server.password.empty?
      end

      # remeber last entered server
      session[:server_id] = params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name, :host, :username, :password, :constant_id)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.haml
= form_for @server do |f|
  - if @server.errors.any?
    #error_explanation
      %h2= t('error.server', count: @server.errors.count)
      %ul
        - @server.errors.full_messages.each do |msg|
          %li= msg
  .panel
    %h3= f.label :name
    .pc= f.text_field :name, autofocus: true
  .panel
    %h3= f.label :host
    .pc= f.text_field :host
  .panel
    %h3= f.label :username
    .pc= f.text_field :username, autocomplete: :off
  .panel
    - if @server.id
      %h3
        = f.check_box :need_password
        = f.label :need_password, t('helpers.label.server.password')
      .pc
        = f.password_field :password, placeholder: t('leave_blank_if_no_changes')
    - else
      %h3= f.label :password
      .pc= f.password_field :password
  .panel
    %h3= f.label :constant_id, t("Private_Key_Constant")
    .pc
      .select= f.collection_select :constant_id, Constant.all, :id, :name, include_blank: "(none)"
  .separator
  .actions
    - if @server.id
      = hidden_field_tag "referrer", request.referrer
      = f.submit t('Save_and_go_back_to_previous_page'), name: "save_and_go_back", class: "button button-green"
    = f.submit t('Save'), class: "button button-green"

app/views/servers/_menu.html.haml
#submenu.button_group
  = link_to servers_path, class: "button button-list#{active_action? %w(index)}" do
    %span.icon= t('Listing_Servers')
  - server_id = @server.try(:id)
  - server_id = session[:server_id] if server_id.nil? and session[:server_id].present?
  - if server_id.present?
    = link_to server_path(server_id), class: "button button-details#{active_action? %w(show)}" do
      %span.icon= t('Server_Details')
    = link_to edit_server_path(server_id), class: "button button-edit#{active_action? %w(edit update)}" do
      %span.icon= t('Edit_Server')
    = link_to delete_server_path(server_id), title: t('Delete_Server'), class: "button button-delete button-red delete#{active_action? %w(delete)}" do
      %span.icon
  = link_to new_server_path, class: "button button-new button-green#{active_action? %w(new create)}" do
    %span.icon= t('New_Server')
.menu_div

app/views/servers/delete.html.haml
= render 'menu'

.panel.max
  %h3= t("Deleting_Server", server: @server.name)
  .confirm
    = t('Delete_Server_Confirm')
    %br
    = t('Delete_Server_Jobs_Related', count: @server.jobs.count)
    .buttons
      = link_to t('Delete_Server_Yes'), server_path(@server), method: :delete, data: { confirm: t('Delete_Server_Confirm') }, class: "button button-red"

app/views/servers/index.html.haml
= render 'menu'
:css
  @media only screen and (max-width: 480px) {
    table#servers td:nth-of-type(1):before { content: "ID"; }
    table#servers td:nth-of-type(2):before { content: "#{t('helpers.label.server.name')}"; }
    table#servers td:nth-of-type(3):before { content: "#{t('helpers.label.server.host')}"; }
    table#servers td:nth-of-type(4):before { content: "#{t('helpers.label.server.username')}"; }
    table#servers td:nth-of-type(5):before { content: "#{t('helpers.label.server.jobs')}"; }
  }
%table#servers.list
  %thead
    %tr
      %th ID
      %th= t('helpers.label.server.name')
      %th= t('helpers.label.server.host')
      %th= t('helpers.label.server.username')
      %th= t('helpers.label.server.jobs')
  %tfoot
    %tr
      %td{ colspan: 5 }
        = t("server", count: @servers.size)
  %tbody
    - @servers.each do |server|
      %tr
        %td= server.id
        %td
          = link_to server.name, server
          = link_to(t('Change_Key'), edit_server_path(server), title: t('Change_Key'), class: "key") if server.constant.present?
        %td= server.host
        %td= server.username
        %td= server.jobs.count

app/views/servers/show.html.haml
= render 'menu'

.panel.float
  %h3= t('helpers.label.server.name')
  .pc
    = @server.name
.panel.float
  %h3= t('helpers.label.server.host')
  .pc
    = @server.host
.panel.float
  %h3= t('helpers.label.server.userpass')
  .pc
    = "#{@server.username} (" + (@server.password.blank? ? t("no_password") : "*" * @server.password.length) +  ")"
.panel.float
  %h3= t('Private_Key_Constant')
  .pc
    = @server.constant.present? ? link_to(@server.constant.name, settings_path) : t("none")

.clear
.separator

- if @server.jobs.size == 0
  .field
    = link_to t('create_blank_job'), create_blank_job_for_server_path(@server), method: :post, class: "button button-blue"
- else
  :css
    @media only screen and (max-width: 480px) {
      table#jobs td:nth-of-type(1):before { content: "ID"; }
      table#jobs td:nth-of-type(2):before { content: "#{t('helpers.label.job.name')}"; }
      table#jobs td:nth-of-type(3):before { content: "#{t('helpers.label.job.Updated_At')}"; }
    }
  %table#jobs.list
    %thead
      %tr
        %th ID
        %th= t('helpers.label.job.name')
        %th.date= t('helpers.label.job.Updated_At')
    %tfoot
      %tr
        %td{ colspan: 3 }
          = t("related_job", count: @server.jobs.size)
    %tbody
      - @server.jobs.each do |job|
        %tr
          %td= job.id
          %td
            = link_to job.name, job
            %span.interpreter
              = job.interpreter.try(:path).presence || "Script"
          %td.date
            %abbr.timeago{ title: job.updated_at.getutc.iso8601 }
              = job.updated_at

%script<= raw jquery_timeago_tranlations