config/routes.rb
EasyJobs::Application.routes.draw do
  devise_for :admins, :controllers => { :sessions => "sessions" }

  resources :servers do
    member do
      get :delete
      post :create_blank_job, as: "create_blank_job_for"
    end
  end

  resources :jobs do
    member do
      get :run
      get :token_run
      get :timestats
      delete :timestats, to: "jobs#destroy_timestats"
      get :delete
    end
  end

  resources :admins do
    member do
      get :delete
      post :edit
    end
  end

  get '/settings', to: "settings#index"
  scope '/settings' do
    put :edit_types, to: "settings#update_types"
    put :edit_interpreters, to: "settings#update_interpreters"
    put :edit_constants, to: "settings#update_constants"
    get '/constant/:id', to: "settings#get_constant", as: "get_constant"
    put '/constant/:id', to: "settings#update_content_of_constant", as: "edit_content_of_constant"
  end

  root to: "jobs#index"

  get '/token_login/*token', to: "application#token_login", as: "token_login", format: false

  namespace :api do
    namespace :v1 do
      get :help
      get :parameters
      delete :tokens, as: "revoke_token"
      resources :jobs, only: [:index, :show] do
        get :run
      end
    end
  end

  

end

app/views/layouts/_head.html.haml
%meta{ charset: 'UTF-8' }
%meta{ name: 'description', content: 'A simple Ruby on Rails SSH web interface to ease your workload.' }
%meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' }
%title EasyJobs
%link{ rel: 'shortcut icon', href: '/favicon.ico' }
%link{ rel: 'icon', href: '/assets/icons/EasyJobs_152px.png' }
%link{ rel: 'apple-touch-icon-precomposed', href: '/assets/icons/EasyJobs_152px.png' }
= javascript_include_tag "fastclick", "data-turbolinks-track" => true

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render '/layouts/head'
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #na_container
      - if notice
        #notice
          = notice
          %a.close{ href: "#" } x
      - if alert
        #alert
          = alert
          %a.close{ href: "#" } x
    #wrapper
      #main
        #header
          %h1#title
            EasyJobs
            .right
              = link_to current_admin.username, edit_admin_path(current_admin)
              |
              - I18n.available_locales.each do |locale|
                - if I18n.locale.to_s == locale.to_s
                  %b= t(locale, locale: locale)
                - else
                  = link_to t(locale, locale: locale), { locale: locale }
              |
              = link_to t('Log_Out'), destroy_admin_session_path, method: :delete
        #menu.button_group
          = link_to t('Jobs'), jobs_path, class: "button" + (params[:controller]=="jobs" ? " active" : "")
          = link_to t('Servers'), servers_path, class: "button" + (params[:controller]=="servers" ? " active" : "")
          = link_to t('Admins'), admins_path, class: "button" + (params[:controller]=="admins" ? " active" : "")
          = link_to t('Settings'), settings_path, class: "button" + (params[:controller]=="settings" ? " active" : "")
        = yield

app/views/layouts/application_small.html.haml
!!!
%html
  %head
    = render '/layouts/head'
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #na_container
      - if notice
        #notice
          = notice
      - if alert
        #alert
          = alert
    #wrapper
      #main.small
        #header
          %h1#title
            = t('Log_into_EasyJobs')
            .right
              - I18n.available_locales.each do |locale|
                - if I18n.locale.to_s == locale.to_s
                  %b= t(locale, locale: locale)
                - else
                  = link_to t(locale, locale: locale), { locale: locale }
        = yield
    :javascript
      window.addEventListener('load', function() {
        FastClick.attach(document.body);
        setTimeout(function(){
          var nac=document.getElementById('na_container');
          if(nac)document.getElementsByTagName('body')[0].removeChild(nac);
        }, 4000);
      }, false);